# Generated by Django 5.0.1 on 2024-02-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0002_autor_intitucion_autor_nacionalidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='intitucion',
            new_name='institucion',
        ),
    ]
